# Generated by Django 4.0.6 on 2022-10-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='blog_img',
            field=models.ImageField(blank=True, upload_to='blog_pcs'),
        ),
    ]
