# Generated by Django 4.0.6 on 2022-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_image_article_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sneak_peek',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
