# Generated by Django 4.0.6 on 2022-11-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_sneak_peek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_pl',
            field=models.TextField(blank=True),
        ),
    ]
