# Generated by Django 4.0.6 on 2022-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_downloadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadfile',
            name='download_file',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
