# Generated by Django 4.0.6 on 2022-09-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_downloadfile_download_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DownloadFile',
            new_name='Downloads',
        ),
    ]
