# Generated by Django 4.0.6 on 2022-09-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_downloadfile_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='temat',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='contact',
            name='imie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
