# Generated by Django 4.0.6 on 2022-09-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_temat_alter_contact_imie'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
