# Generated by Django 4.0.6 on 2022-10-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_downloads_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
