# Generated by Django 4.0.6 on 2022-10-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_downloads_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='picture',
        ),
    ]
