# Generated by Django 4.0.6 on 2022-08-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('prayer', models.TextField()),
                ('flag', models.ImageField(upload_to='')),
                ('church', models.ImageField(upload_to='')),
                ('church_description', models.CharField(max_length=300)),
            ],
        ),
    ]
