# Generated by Django 4.0.6 on 2022-08-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_pl', models.CharField(blank=True, max_length=150, null=True)),
                ('church_eng', models.CharField(blank=True, max_length=150, null=True)),
                ('church_local', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_pl', models.CharField(blank=True, max_length=100, null=True)),
                ('country_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('country_local', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_text_pl', models.TextField(blank=True, null=True)),
                ('prayer_text_eng', models.TextField(blank=True, null=True)),
                ('prayer_text_local', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='church_description',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='prayer',
        ),
        migrations.AddField(
            model_name='prayer',
            name='church_img',
            field=models.ImageField(blank=True, upload_to='church_img_pcs'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='flag',
            field=models.ImageField(blank=True, upload_to='flag_pcs'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='prayer_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prayer.prayer_text'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer.church'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer.country'),
        ),
    ]
