# Generated by Django 4.0.6 on 2022-08-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0002_church_country_prayer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prayer.country'),
        ),
    ]
