# Generated by Django 4.0.6 on 2022-08-16 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0003_alter_prayer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prayer.church'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prayer.prayer_text'),
        ),
    ]
