# Generated by Django 4.0.6 on 2022-09-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0004_alter_prayer_church_alter_prayer_prayer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer',
            name='date',
        ),
        migrations.AddField(
            model_name='prayer',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='date3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='date4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
