# Generated by Django 4.0.6 on 2022-10-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0005_remove_prayer_date_prayer_date1_prayer_date2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.IntegerField()),
            ],
        ),
    ]
