# Generated by Django 4.0.6 on 2022-10-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0006_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
