# Generated by Django 4.0.6 on 2022-10-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0007_delete_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_img', models.ImageField(blank=True, upload_to='counter_pcs')),
            ],
        ),
    ]
